version = 0.1

[default.deploy.parameters]
stack_name = "xz-wallet-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "xz-wallet-backend"
